# Cuadernillo de Trabajo {#cuadernillo}

Existe un cuadernillo de trabajo que recolecta las actividades básicas que debe realizar un Corderito, por ahora y hasta nuevo aviso estaremos utilizando una versión electrónica del mismo. Tan pronto el Club tenga acceso a adquirir la versión física de los mismos se harán disponibles para cada Corderito.

Para acceder a la versión electrónica del cuadernillo de trabajo puede dar [click aquí.](https://www.dropbox.com/s/34z3sphzbmjmgb4/Cuadernillo%20Corderos.pdf?dl=0)

Es recomendable, pero no obligatorio, que como padres hagamos el esfuerzo de generar una copia física del archivo digital que se comparte en esta página en lo que se tiene acceso a los cuadernillos en físico.

## Objetivo del Nivel de Corderitos

  1. Demostrar el amor de Dios por los niños.
  1. Promover los valores expresados en el voto y ley de Corderitos.
  1. Crear un ambiente en donde todos los niños puedan contribuir.
  1. Estimular a los niños a divertirse.

### El Voto de los Aventureros

  - Por amor a Jesús siemrpe haré lo mejor.

### La Ley de los Aventureros

  <center>
  La ley del aventurero me manda: <br>
  Ser Obediente <br>
  Ser Puro <br>
  Ser Leal <br>
  Ser Bondadoso <br>
  Ser Respetuoso <br>
  Ser Atento <br>
  Ser Útil <br>
  Ser Alegre <br>
  Ser Considerado <br>
  Ser Revernte <br>
  </center>

## Requisitos de Investidura de Corderitos

### Básico
  1. Recitar el voto de los Aventureros.
  1. Cantar el canto tema "Es mi Buen Pastor".

### Mi Dios
  1. Completar tres o más de los siguientes requisitos:
     * Cantar un canto acerca de Jesús.
     * Escuchar una historia acerca de Jesús.
     * Decir tres cosas que aprendiste acerca de Jesús.
     * Hacer una manualidad acerca de Jesús.
     * Completar una actividad acerca de Jesús.
  1. Obtener la estrella de Corderito.
  1. Obtener la estrella El Niño Jesús.

### Yo Mismo
  1. Completar tres o más de los siguientes requisitos:
     - Cantar un canto acerca del cuerpo.
     - Escuchar una historia acerca del cuerpo.
     - Decir tres cosas que aprendiste acerca del cuerpo.
     - Hacer una manualidad acerca del cuerpo.
     - Completar una actividad acerca del cuerpo.
  1. Obtener la estrella de Compartiendo.
  1. Obtener la estrella de Alimentos Sanos.
  
### Mi Familia
  1. Completar tres o más de los siguientes requisitos:
     - Cantar un canto acerca de las familias.
     - Escuchar una historia acerca de las familias.
     - Decir tres cosas que aprendiste acerca de las familias.
     - Hacer una manualidad acerca de las familias.
     - Completar una actividad acerca de las familias.
  1. Obtener la estrella de Ayudante Especial.
  1. Obtener la estrella de Sano y Fuerte.

### Mi Mundo
  1. Completar tres o más de los siguientes requisitos:
     - Cantar un canto acerca de la creación.
     - Escuchar una historia acerca de la creación.
     - Decir tres cosas que aprendiste acerca de la creación.
     - Hacer una manualidad acerca de la creación.
     - Completar una actividad acerca de la creación.
  1. Obtener la estrella de Mi Amigo Jesús.
  1. Obtener la estrella Ayudantes de la Comunidad.
